notify:
  description: send Notify to Line Using Line Notify.
  # Different fields that your service accepts
  fields:
    # Key of the field
    data:
      # Description of the field
      description: data send
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: { "url": "https://picsum.photos/600/400" }
    message:
      description: message to line
      required: true
      example: "Hello"